"""Add jlikes

Revision ID: b997a6634219
Revises: 
Create Date: 2024-12-31 20:45:25.797115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b997a6634219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('j_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('j_dislikes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('j_dislikes')
        batch_op.drop_column('j_likes')

    # ### end Alembic commands ###
